version: "3.9"
services:
    devenv:
        image: "ubuntu:latest"
        container_name: "roofus"
        ports:
            - "80:80"
            - "443: 443"
        stdin_open: true
        volumes:
            - devenv:/root/roofus
volumes:
    devenv: